name: Wedding API deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Dependencies
        run: |
          composer install
          cp .env.example .env
          php artisan key:generate --ansi

      - name: Deploy Laravel Project
        if: github.ref == 'refs/heads/main'
        run: |
          # Deploy application files
          sshpass -p 'Seni@ti12345' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@195.35.23.150://var/www/wedding-bna-api/

          # Update server
          sshpass -p 'Seni@ti12345' ssh -o StrictHostKeyChecking=no root@195.35.23.150 'cd /var/www/wedding-bna-api && php artisan config:cache && php artisan route:cache && php artisan view:cache'

      - name: Set Permissions
        run: |
          sshpass -p 'Seni@ti12345' ssh -o StrictHostKeyChecking=no root@195.35.23.150 'find /var/www/wedding-bna-api/storage/ -type d -exec chmod 775 {} \;'
          sshpass -p 'Seni@ti12345' ssh -o StrictHostKeyChecking=no root@195.35.23.150 'find /var/www/wedding-bna-api/bootstrap/cache/ -type d -exec chmod 775 {} \;'
